name: FRL
version: ${project.version}
author: Simonsator
depends: [ PartyAndFriends ]
depend: [ PartyAndFriends ]
main: de.simonsator.partyandfriends.friendrequestlist.FRL
description: An add-on for party and friends extended to add a list all friend requests
api-version: 1.13