name: FRL
version: ${project.version}
author: Simonsator
depends: [PartyAndFriends]
main: de.simonsator.partyandfriends.friendrequestlist.FRL
description: An add-on for party and friends extended to add a list all friend requests